// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITqhbPmqlHREW6bW7k9XzRozhz-8__5w',
    appId: '1:596307941129:web:b3c77fb96bf90758eba5d8',
    messagingSenderId: '596307941129',
    projectId: 'fir-app-7be70',
    authDomain: 'fir-app-7be70.firebaseapp.com',
    databaseURL: 'https://fir-app-7be70-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-7be70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0xXa1Qzk1OMSr_Qk111Gowhku68-jtg',
    appId: '1:596307941129:android:e725464c2da72d6feba5d8',
    messagingSenderId: '596307941129',
    projectId: 'fir-app-7be70',
    databaseURL: 'https://fir-app-7be70-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-7be70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6N55W8ow4lI9BuUAj3E0W9KJJPU1VUY',
    appId: '1:596307941129:ios:054e81983d10c7c4eba5d8',
    messagingSenderId: '596307941129',
    projectId: 'fir-app-7be70',
    databaseURL: 'https://fir-app-7be70-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-7be70.appspot.com',
    iosClientId:
        '596307941129-ilf7gaq16aqbbjudjngifv0g5f0tc44k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6N55W8ow4lI9BuUAj3E0W9KJJPU1VUY',
    appId: '1:596307941129:ios:d048caf38db9774eeba5d8',
    messagingSenderId: '596307941129',
    projectId: 'fir-app-7be70',
    databaseURL: 'https://fir-app-7be70-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-7be70.appspot.com',
    iosClientId:
        '596307941129-jmfimcn8oc0on7ncnce666lu3bords9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStart.RunnerTests',
  );
}
